#pragma once

#include "frame.h"

class Style
{
public:

	enum {
		WINDOW = 0,
		WINDOW_TITLE,
		WINDOW_TITLE_LABEL,
		WINDOW_BUTTON,
		WINDOW_BUTTON_HILITE,
		WINDOW_BUTTON_PRESSED,
		WINDOW_BUTTON_DISABLED,
		UNFOCUS_WINDOW,
		UNFOCUS_WINDOW_TITLE,
		UNFOCUS_WINDOW_TITLE_LABEL,
		UNFOCUS_WINDOW_BUTTON,
		UNFOCUS_WINDOW_BUTTON_HILITE,
		UNFOCUS_WINDOW_BUTTON_PRESSED,
		UNFOCUS_WINDOW_BUTTON_DISABLED,

		TASKBAR,
		TASKBAR_BUTTON,
		TASKBAR_BUTTON_HILITE,
		TASKBAR_BUTTON_PRESSED,
		TASKBAR_BUTTON_ACTIVE,
		TASKBAR_CLOCK,
		TASKBAR_DESKTOP_BUTTON,
		TASKBAR_DESKTOP_BUTTON_HILITE,
		TASKBAR_DESKTOP_BUTTON_PRESSED,

		START_MENU,
		START_MENU_ITEM,
		START_MENU_ITEM_HILITE,
		START_MENU_ITEM_PRESSED,
		START_MENU_SHUTDOWN,
		START_MENU_SHUTDOWN_HILITE,
		START_MENU_SHUTDOWN_HILITE_PRESSED,
		START_MENU_PROGRAMS,
		START_MENU_PROGRAMS_ITEM,
		START_MENU_PROGRAMS_ITEM_HILITE,
		START_MENU_PROGRAMS_ITEM_PRESSED,

		FRAMES_COUNT
	};

	Frame frames[FRAMES_COUNT];

	virtual bool load(const QString& filename);

protected:
	virtual QColor readColor(QString clr, QColor defaultColor);
};